### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by Hans2573** [YangZhengyi98/DreamRec#3]
您好请问一下，
论文中使用的数据集，而不是推荐领域中的其他数据集，如 Movielens、Amazon数据集，

是有什么额外的考量吗？

**Comment by Hans2573** [comment]
![image](https://github.com/YangZhengyi98/DreamRec/assets/70685549/713f5872-6ae4-4606-bc8f-1f67c5edef1e)

论文和代码中提供的数据集，

这里的第0行，和第1行，序列长度都是1吗？ 我理解第一行应该是0吧。

**Comment by YangZhengyi98** [comment]
感谢提问！

前两个数据集（YooChoose&KuaiRec）直接用的我们在SIGIR 2023工作DROS（https://github.com/YangZhengyi98/DROS ） 的数据集。但DROS的第三个数据集RetailRocket规模较大，用在DreamRec上采样时间很长，资源有限难以大规模调参。因此我们在Zhihu1M和Movielens1M上进行实验，ddl前Zhihu数据效果更好，因此选择其作为第三个数据。

代码中因为序列长度设为0在GRU和self attention中无法取出相应hidden-state，故设为1，可认为是trivial data point。

**Comment by Hans2573** [comment]
感谢您的回复，通过这几天的进一步对代码论文的研读，仍想向您请教：

DreamRec 序列长度固定为10，作为序列推荐这个值会不会太短了，本文也没有把长度作为超参数；
SASRec、GRU4Rec，序列长度可以调整，如50,100， （dataset eg， ML，Amazon等）

“For all datasets, we first sort all sequences in chronological order, and then split the data into training, validation and testing data at the ratio of 8:1:1.”
这种做法，我理解通常是协同过滤对数据集的处理。序列推荐模型通常使用的“leave one out” 的方式处理数据集。
序列推荐的训练集，每个样本是按照时间顺序排好的，本文（8:1:1）不同样本间按照的时间顺序，是指用户最后一次交互的时间作为这个样本的时间，然后所有样本排序，是这样的吗？

所以对数据集的选择，和处理方式，仍有困惑。
另外，本文提供的数据集是直接处理好的，是否方便提供处理流程，方便应用于其他数据集，修改序列长度等。
（email：hangkees@aliyun.com）

非常感谢！

**Comment by YangZhengyi98** [comment]
> 有做过序列长度为20，30的实验，结果类似。

> 按照时间将不同的序列划分目的在于防止潜在的‘未来’交互出现在训练集中，详见[1].

> 已发。

[1] A critical study on data leakage in recommender system offline evaluation. ACM TOIS, 2023, 41(3): 1-27.

**Comment by Hiilay** [comment]
数据的处理流程能否也发我一遍，感谢！
（email：hiilay@163.com）

**Comment by Dreamhepeng** [comment]
> 数据的处理流程能否也发我一遍，感谢！ （email：[hiilay@163.com](mailto:hiilay@163.com)）

您好，很抱歉打扰您，您解决了数据处理的问题了嘛，能否也发我一遍呢，感谢！ （email：hepengkg@gmail.com）
