### ISSUE TITLE
这篇论文中的扩散模型优化序列推荐的核心问题是什么?

### ISSUE THREAD

**Issue by Hans2573** [YangZhengyi98/DreamRec#5]
您好，

虽然本文用到了扩散模型，但感觉真正起作用的仍然是Tansformer结构。

所以想请教一下，本文使用扩散模型，加噪，降噪这个过程，对序列推荐任务的增益在什么地方？

十分感谢！

**Comment by YangZhengyi98** [comment]
本文核心在于将序列推荐重新建模为了基于隐变量生成任务，区别于之前的判别任务，扩散模型是为了完成生成任务。

> 扩散模型和Transformer网络是不能比较的，扩散模型是生成范式，定义了整个学习过程；Transformer是网络结构，实现数据编码功能。

> 加噪降噪不直接影响推荐，是在扩散模型定义的学习范式之内。以前的隐变量生成模型（GAN，VAE）也涉及高斯噪声。

**Comment by Hans2573** [comment]
感谢！
