### ISSUE TITLE
数据集处理相关

### ISSUE THREAD

**Issue by Hiilay** [YangZhengyi98/DreamRec#8]
大佬您好！这篇论文提供的数据集已经经过处理，请问是否方便提供数据集处理流程，方便应用于其他数据集，修改序列长度等。
邮箱hiilay@163.com
感谢！盼复！

**Comment by Torres-Code** [comment]
+1 
邮箱790726278@qq.com
感谢！

**Comment by Dreamhepeng** [comment]
你们找到解决办法了吗？
